# flask-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: newpow-service
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000   