# postgres-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: bXlhcHBkYg==      # base64 encoded 'myappdb'
  POSTGRES_USER: cG9zdGdyZXM=    # base64 encoded 'postgres'
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # base64 encoded 'password'